app:
  name: "messaggio"
  version: "1.0.0"

postgres:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "qwerty"
  connAttempts: 10
  connTimeout: "1ms"

http:
  port: 8888

log:
  level: "debug"

kafka:
  brokers: "kafka:9092"
  topic: "messaggio"